version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "30000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - type: bind
        source: C:/local-app/todo-app
        target: /app/server/data
    restart: unless-stopped 
    